version: "3.7"
services:
  mongodb:
    image: mongo:5.0
    container_name: mongo-container
    environment:
      MONGO_INITDB_ROOT_USERNAME: 'admin'
      MONGO_INITDB_ROOT_PASSWORD: 'admin'
    ports:
      - 27022:27017
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped
    networks:
      - hh_network_private # only in private network, not map port
  next-app:
    image: nextjs-docker
    container_name: next-container
    restart: always
    ports:
      - 3000:3000
    networks:
      - hh_network

  node-container:
    container_name: node-container
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
    ports:
      - 3001:3001
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:3001/health" ]
      interval: 30s
      timeout: 10s
      retries: 3

    networks:
      - hh_network
      - hh_network_private
    depends_on:
      - mongodb

networks:
  hh_network:
    external: true # using external, don't create new network
    name: hh_network_name
  hh_network_private:
    internal: true # not public port
    external: false
    name: hh_network_private
volumes:
  mongo-data: # external: true 
