version: "3.7"
services:
  mongodb:
    image: mongo:5.0
    container_name: mongo-container
    environment:
      MONGO_INITDB_ROOT_USERNAME: 'admin'
      MONGO_INITDB_ROOT_PASSWORD: 'admin'
    ports:
      - 27022:27017
    restart: unless-stopped
